### PR TITLE
feat: fail arg for errors

### PR DESCRIPTION
**Pull request by splix**
Command line option to fail (exit 1) if a non-green license found. Useful for CI use

### CODE REVIEW

**Comment by ofrobots** [comment]
Hi @splix. Thanks for the PR. This seems to be a regression I introduced in https://github.com/google/js-green-licenses/pull/65. Thanks for fixing it. I think it should be the default for `setExitCode` to `true` – users shouldn't have to pass a flag. Can you make that change?

If the tests give you trouble, let me know, I'd be happy to take a look and get the tests fixed.

**Comment by splix** [comment]
Sure, I can make it as a default option. I though it would break existing contract. Should I make an option to exit 0 if non-green found?

**Comment by ofrobots** [comment]
I don't think this breaks the existing contract. The version of the package published to npm does exit with a non-zero exit code on a non-green license. The regression on the master branch was not released to users.

I don't think we need an option at all.

**Comment by splix** [comment]
@ofrobots please take a look at updated version

**Pull request merged**
